### PR TITLE
Fix the conflict with the prettier.

### PR DESCRIPTION
**Pull request by roneyrogerio**

### CODE REVIEW

**Review by flaviostutz — CHANGES_REQUESTED** [review]
What does it means "0"? In the documentation they don't have it, maybe it would be nice to use a expanded configuration to make it clearer. https://eslint.org/docs/latest/rules/function-paren-newline

**Comment by roneyrogerio** [comment]
I tried with all the options of the documentation, the only way I found was with the value 0 (or 'off') that apparently disables this configuration.

**Comment by roneyrogerio** [comment]
Details of this value is in https://eslint.org/docs/latest/use/configure/rules

**Comment by flaviostutz** [comment]
We don't want to disable this config because it's nice to break line when we have lots of parameters, so we could at most easy the number of parameters per line.

**Comment by roneyrogerio** [comment]
The Prettier will break a line before a parenthesis in some cases. I could not solve this problem with any of the documented settings of the `function-paren-newline` that does not break the validation of another part:
image

**Review by flaviostutz — CHANGES_REQUESTED** [review]
We wouldn't like to disable this rule entirely, at most make it less tight. Can you work on that?

**Comment by flaviostutz** [comment]
Maybe you could take a look at https://github.com/prettier/eslint-plugin-prettier and do a spike

**Comment by roneyrogerio** [comment]
With the last version all problems are solved. thanks.

**Pull request closed without merging**
